language: node_js
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - node_modules
addons:
  firefox: latest
before_install:
  - export MOZ_HEADLESS=1
before_script:
  - yarn install
script:
  - yarn test
