language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  firefox: latest
before_install:
  - export MOZ_HEADLESS=1
before_script:
  - npm install
script:
  - npm test
