import {
  // utils
  allare,
  each,
  flatten,
  compose,
  curry,
  run,
  runAsync,
  query,
  queryAsync,
  queryAll,
  queryEach,
  // type testing
  isArr,
  isComponent,
  isNil,
  isDef,
  isObj,
  isFunc,
  isBool,
  isStr,
  isNum,
  isArrlike,
  isNodeList,
  isNode,
  isModel,
  isMounted,
  isPrimitive,
  isPromise,
  isProxyNode,
  isRenderable,
  isRegExp,
  isInt,
  isInput,
  isEmpty,
  isEl,
  isSvg
} from './common.js'
import emitter from './emitter.js'
import {component, components} from './components.js'
import {attributeObserver, directive, directives} from './directives.js'
import {domfn, render, prime} from './dom-functions.js'
import {dom, fastdom, svg, html} from './dom-generation.js'
import {Mounted, Unmounted, Created} from './lifecycles.js'
import {on, once} from './event-manager.js'
import {model, map2json} from './model.js'
import $ from './proxy-node.js'

export {
  isArr,
  isComponent,
  isNil,
  isDef,
  isObj,
  isFunc,
  isBool,
  isStr,
  isNum,
  isArrlike,
  isNodeList,
  isNode,
  isModel,
  isMounted,
  isPrimitive,
  isPromise,
  isProxyNode,
  isRenderable,
  isRegExp,
  isInt,
  isInput,
  isEmpty,
  isEl,
  isSvg,
  allare,
  attributeObserver,
  flatten,
  curry,
  compose,
  components,
  component,
  run,
  render,
  runAsync,
  query,
  queryAsync,
  queryAll,
  queryEach,
  on,
  once,
  emitter,
  each,
  svg,
  fastdom,
  dom,
  domfn,
  html,
  directive,
  directives,
  prime,
  map2json,
  model,
  Mounted,
  Unmounted,
  Created,
  $
}
